FROM ubuntu:18.04

COPY sources.list /etc/apt/sources.list
COPY main.image.py main.py
COPY requirements.image.txt .

RUN apt-get update && apt-get install -y python3-pip git && \
    pip install --no-cache-dir -r requirements.image.txt

ENV PYTHONUNBUFFERED=1

CMD ["python3", "-u", "main.py"]